//
//  AIInsightsExporter.swift
//  Habitra
//
//  Phase 3 Week 11: Export AI insights as shareable text
//

import Foundation

/// Generates shareable text summaries of AI insights and predictions.
@MainActor
enum AIInsightsExporter {

    /// Generate a complete AI report as shareable text.
    static func generateReport(
        habits: [Habit],
        moodEntries: [MoodEntry] = [],
        insights: [HabitInsight],
        predictions: [HabitPrediction],
        healthScores: [HabitHealthScore]
    ) -> String {
        var lines: [String] = []

        lines.append("📊 HABITRA AI REPORT")
        lines.append("Generated \(Date().formatted(.dateTime.month(.wide).day().year()))")
        lines.append("")

        // Overall health
        if !healthScores.isEmpty {
            let avgScore = healthScores.reduce(0) { $0 + $1.score } / healthScores.count
            lines.append("🏥 OVERALL HEALTH: \(avgScore)/100")
            lines.append("")

            for score in healthScores.prefix(10) {
                let trend = score.trend == .improving ? "↑" : score.trend == .declining ? "↓" : "→"
                lines.append("  \(score.grade.rawValue) \(score.habitName) — \(score.score)/100 \(trend)")
            }
            lines.append("")
        }

        // Tomorrow's forecast
        if !predictions.isEmpty {
            lines.append("🔮 TOMORROW'S FORECAST")
            for pred in predictions {
                let emoji = pred.riskLevel == .high ? "🔴" : pred.riskLevel == .moderate ? "🟡" : "🟢"
                lines.append("  \(emoji) \(pred.habitName): \(Int(pred.successProbability * 100))% (\(pred.riskLevel.label))")
            }
            lines.append("")
        }

        // Key insights
        if !insights.isEmpty {
            lines.append("💡 KEY INSIGHTS")
            for insight in insights.prefix(5) {
                lines.append("  • \(insight.title): \(insight.message)")
            }
            lines.append("")
        }

        // Mood summary
        if !moodEntries.isEmpty {
            let recentMoods = moodEntries.prefix(7)
            let avgMood = Double(recentMoods.reduce(0) { $0 + $1.moodLevel }) / Double(recentMoods.count)
            let moodEmoji = (MoodLevel(rawValue: Int(avgMood.rounded())) ?? .okay).emoji
            lines.append("😊 MOOD: \(moodEmoji) Average \(String(format: "%.1f", avgMood))/5 (last 7 entries)")
            lines.append("")
        }

        lines.append("—")
        lines.append("Generated by Habitra — on-device AI, zero cloud")

        return lines.joined(separator: "\n")
    }

    /// Generate a short summary suitable for social sharing.
    static func generateShortSummary(
        habits: [Habit],
        healthScores: [HabitHealthScore]
    ) -> String {
        let activeCount = habits.filter { !$0.isArchived }.count
        let avgScore = healthScores.isEmpty ? 0 :
            healthScores.reduce(0) { $0 + $1.score } / healthScores.count

        let bestStreak = habits.map(\.currentStreak).max() ?? 0
        let avgRate = StreakCalculator.averageWeeklyRate(habits: habits.filter { !$0.isArchived })

        return """
        📊 My Habitra Stats
        🏥 Health Score: \(avgScore)/100
        🔥 Best Streak: \(bestStreak) days
        ✅ Weekly Rate: \(Int(avgRate * 100))%
        📱 Tracking \(activeCount) habits

        Tracked with Habitra — private AI habit coach
        """
    }
}
